### ISSUE TITLE
TypeError: Mongo.withTransaction is not a function after upgrading to Meteor 3.3.1

### ISSUE THREAD

**Issue by mcorbelli** [jamauro/mongo-transactions#8]
After upgrading our project to Meteor 3.3.1 (along with the mongo package to version 2.1.3), we started encountering the following error when using jam:mongo-transactions:

`TypeError: Mongo.withTransaction is not a function`

It seems that jam:mongo-transactions is no longer compatible with the updated mongo driver. Unfortunately, we had to upgrade to Meteor 3.3.1 to take advantage of the new default transpiler for certain features in our project.

**Comment by jamauro** [comment]
I can't reproduce this on a fresh install of Meteor `3.3.1` 

Are you using `v1.2.1`of this package? If so, did you try this? https://github.com/jamauro/mongo-transactions?tab=readme-ov-file#typescript

**Comment by mcorbelli** [comment]
We were able to resolve the issue on our side. Everything is now working correctly with Meteor 3.3.1 and the updated mongo package.

The issue can be closed.
